Updated to java17
aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner pull request #63
Opened 2024-03-05 02:21 UTC by shantgup

*Issue #62 

*Description of changes:* Updated to Java17 runtime.

2024-03-08 18:22 UTC, himanshs23 approved these changes

2024-03-08 23:36 UTC, rclinard-amzn requested changes
Two small nits.

2024-03-08 23:36 UTC, rclinard-amzn commented on resource-role.yaml
> +                - "logs:PutMetricData"
I think this would still be `cloudwatch:PutMetricData`.

2024-03-08 23:36 UTC, rclinard-amzn commented on .DS_Store
Let's delete this file. It should probably be in the `.gitignore`

2024-03-08 23:49 UTC, rclinard-amzn approved these changes

2024-03-09 01:23 UTC, himanshs23 approved these changes

2024-03-09 01:25 UTC, merged